title: My Notes
description: Study plans and notes
theme: jekyll-theme-minimal

# Lets links between .md files work on the site and on GitHub itself
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
